### ISSUE TITLE
tsyringe requires a reflect polyfill. Please add 'import "reflect-metadata"' to the top of your entry point.

### ISSUE THREAD

**Issue by ryceg** [navneetsharmaui/sveltekit-starter#11]
On a fresh install of the template, following instructions exactly the following error is received:

```Error: tsyringe requires a reflect polyfill. Please add 'import "reflect-metadata"' to the top of your entry point.
    at Object.<anonymous> (/Users/admin/github/project-sprawl/node_modules/tsyringe/dist/cjs/index.js:5:11)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at nodeRequire (/Users/admin/github/project-sprawl/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68211:17)
    at ssrImport (/Users/admin/github/project-sprawl/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68164:20)
    at eval (/src/lib/core/services/https/http-json.ts:14:31)```

**Comment by ashleyconnor** [comment]
Add `import "reflect-metadata"` to the top of `src/lib/core/core.ts` as a temporary workaround.

**Comment by navneetsharmaui** [comment]
@ashleyconnor @ryceg this issue is fixed. Thanks for waiting.
